### ISSUE TITLE
Add fields to tree table in database

### ISSUE THREAD

**Issue by doriengr** [green-ecolution/green-ecolution-backend#68]
- [x] Flag: Is the tree imported or created manually
- [x] Tree-Number needs to be a string because it's also possible to add `B 123` or `P 334`
- [ ] ~~Flag: Is the tree owned by the TBZ or elsewhere?~~
- [ ] Discuss: Do we need a street-name/address?

**Comment by choffmann** [comment]
@ShadowDataNerd @doriengr Do we really need the flag if the tree is imported or not? Let's start with the scenario from TBZ. If a tree is imported, we wanted to add this flag to merge this tree with the data that may have been revised in the meantime during a new import. Why don't we get it from the TBZ 'id' (lat + long)? If this 'id' exists, do we assume that this tree is from the import? Again, this is too TBZ specific for me

**Comment by choffmann** [comment]
@ShadowDataNerd 

Okay, @doriengr and I have discussed that we need a flag to determine if the tree is readonly or editable. So we don't need a flag to check if the tree is imported or not, but if the tree is readonly or not.

**Comment by xk0niR** [comment]
@ShadowDataNerd 
After discussing with @doriengr and @choffmann and @Mohammad96Assaf 

Please also remove age and height_above_sea_level from the table tree.
