### ISSUE TITLE
Error handler always return status 500

### ISSUE THREAD

**Issue by choffmann** [green-ecolution/green-ecolution-backend#70]
Has to be like this in `internal/server/http/server.go`

```go
func errorHandler(c *fiber.Ctx, err error) error {
	code := fiber.StatusInternalServerError

	var e *fiber.Error
	if errors.As(err, &e) {
		code = e.Code
		return c.Status(code).JSON(HTTPError{
			e.Message,
			e.Code,
			c.Path(),
			c.Method(),
		})
	}
	return nil
}
```

**Comment by techyoichiro** [comment]
Hello! @choffmann !
I'd like to contribute to this project and noticed issue #70 about the error handler always returning a status 500. Would it be alright if I take on this issue? I'll follow the suggested fix mentioned in the issue description.

Looking forward to your confirmation!

Thanks in advance.

**Comment by choffmann** [comment]
Hello @techyoichiro, I am glad to hear that you are interested in this project. However, this is a university research project that will be graded at the end. I will ask my lecturer next Tuesday if I can accept contributors.

**Comment by techyoichiro** [comment]
@choffmann 
Oh, I see! Got it, no worries. Thanks for letting me know and taking the time to explain!

**Comment by techyoichiro** [comment]
@choffmann Thank you!
I'll go ahead and fix it and submit a pull request!
Do you have any specific format for the branch name or commit message?

**Comment by choffmann** [comment]
@techyoichiro please use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) and branch names in git flow style with a prefix like `feature/*`
